<%@ Page Title="" Language="C#" MasterPageFile="~/User/User.master" AutoEventWireup="true" CodeFile="Termsandconditions.aspx.cs" Inherits="User_Terms_and_conditions" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style12
    {
        font-size: xx-large;
        color: #003366;
    }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
<table cellpadding="4" class="style7">
    <tr>
        <td style="text-align: center; font-family: Arial, Helvetica, sans-serif"><span class="style12">TERMS &amp; CONDITIONS</span>
            <hr noshade="noshade" style="color: #FF0000; background-color: #FF0000; width: 1200px;" width="550" />
        </td>
    </tr>
    <tr>
        <td style="font-family: Arial, Helvetica, sans-serif; color: #000000">
            <p>
                &nbsp;</p>
            <ul>
                <li>Home Services works with freelancers as an aggregator. The invoice will be generated by the serviceman who visits the customer to do the job </li>
            </ul>
            <p>
                &nbsp;</p>
            <ul>
                <li>An estimate on behalf of serviceman will be shared via phone. If you require a bill&nbsp; then please contact our customer support desk at 9309160006 . An invoice will get re-generated with applicable taxes. </li>
            </ul>
            <p>
                &nbsp;</p>
            <ul>
                <li>A warranty of 10 days is applicable on all services delivered, for all bookings made through Extreme Call Center or Extreme website. </li>
            </ul>
            <p>
                &nbsp;</p>
            <ul>
                <li>Minimum visiting charges of Rs 250 will be applicable if no work is done after the visit has been made by the technician. In case the service amount is less than Rs 250, same will be charged - if the service amount is more than the visiting charges, no visiting charges will be added.</li>
            </ul>
            <p>
                &nbsp;</p>
        </td>
    </tr>
</table>
</asp:Content>

